### ISSUE TITLE
Looking for collaborators

### ISSUE THREAD

**Issue by ZiadJ** [uranixcz/resource_mng#1]
Hi, I've been working on a similar concept for a while but on a much larger scale and because of that I haven't been able to publish anything yet by lack of time. So I thought we could collaborate may be and share the load.

**Comment by uranixcz** [comment]
Hi, I would love that. However the only languages I can use "well" is Rust and Java and I strongly prefer Rust. Rust can call or be called from C and possibly compatible languages. I'm a hobby programmer so if you have experience with software projects that would be great because I don't know much about collaboration or git.

If you still want to talk then I will send you my skype name via email. I am also available on discord and mumble.

**Comment by uranixcz** [comment]
We keep in touch on fb.
